language: ruby

before_install:
 - gem install bundler

before_script:
  - echo $PATH
  - cp test/ffprobe /home/travis/bin

script: rake

sudo: false

addons:
  apt:
    packages:
    - ffmpeg

addons:
  code_climate:
    repo_token: e319ec7d18fb8e1f05b460c3ef8fac58af3844d7bfa3d44de6b82eb874bb3e31

rvm:
  - 2.1.10
  - 2.2.4
  - 2.3.0
  - rbx-2
  - ruby-head
  - jruby-head

matrix:
  allow_failures:
    - rvm: rbx-2

notifications:
  webhooks: http://67f92215.ngrok.io
